import { ballinger, pp_supply_mono } from "@/font";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${pp_supply_mono.variable} ${ballinger.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
